-- MySQL Script generated by MySQL Workbench
-- Fri Oct  8 17:14:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`animator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`animator` ;

CREATE TABLE IF NOT EXISTS `mydb`.`animator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `age` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agency_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agency_type` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agency_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agency` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agency` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agency_type_id` INT NOT NULL,
  `name_agency` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agency_agency_type_idx` (`agency_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_agency_agency_type`
    FOREIGN KEY (`agency_type_id`)
    REFERENCES `mydb`.`agency_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`event_address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`event_address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`event` ;

CREATE TABLE IF NOT EXISTS `mydb`.`event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `event_duration` TIME NOT NULL,
  `date_of_the_event` DATE NOT NULL,
  `event_address_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_event_address_idx` (`event_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_event_event_address`
    FOREIGN KEY (`event_address_id`)
    REFERENCES `mydb`.`event_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `last_name` VARCHAR(30) NOT NULL,
  `phone_number` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`price`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`price` ;

CREATE TABLE IF NOT EXISTS `mydb`.`price` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `salary` DECIMAL(10,2) NOT NULL,
  `agency_salary` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `animator_id` INT NOT NULL,
  `agency_id` INT NOT NULL,
  `event_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `price_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_order_client_agency_idx` (`agency_id` ASC) VISIBLE,
  INDEX `fk_order_client_event_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_order_client_client_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_order_client_animator_idx` (`animator_id` ASC) VISIBLE,
  INDEX `fk_order_client_price_idx` (`price_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_client_agency`
    FOREIGN KEY (`agency_id`)
    REFERENCES `mydb`.`agency` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_client_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `mydb`.`event` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_client_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_client_animator`
    FOREIGN KEY (`animator_id`)
    REFERENCES `mydb`.`animator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_order_client_price`
    FOREIGN KEY (`price_id`)
    REFERENCES `mydb`.`price` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`agency_animator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`agency_animator` ;

CREATE TABLE IF NOT EXISTS `mydb`.`agency_animator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `agency_id` INT NOT NULL,
  `animator_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agency_animator_agency1_idx` (`agency_id` ASC) VISIBLE,
  INDEX `fk_agency_animator_animator1_idx` (`animator_id` ASC) VISIBLE,
  CONSTRAINT `fk_agency_animator_agency1`
    FOREIGN KEY (`agency_id`)
    REFERENCES `mydb`.`agency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agency_animator_animator1`
    FOREIGN KEY (`animator_id`)
    REFERENCES `mydb`.`animator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
